---

version: 0.0

os: linux

files:
  - source: ./
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: ./codedeploy/beforeinstall.sh
      runas: ec2-user
  AfterInstall:
    - location: ./codedeploy/afterinstall.sh
      runas: ec2-user
  ApplicationStart:
    - location: ./codedeploy/applicationstart.sh
      runas: ec2-user