---
name: Packer Validate on Pull Requests

# Controls when the action will run.
# Triggers the workflow on pull request events but only for the main branch
on:
  # Workflow is triggered on pull requests
  pull_request:
    # Workflow will only be triggered for pull requests on "main" branch
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - run: zip -r webservice.zip ./
    - run: pwd
    - run: ls

      # Initialize Packer templates
    - name: Initialize Packer Template
      uses: hashicorp/packer-github-actions@master
      with:
          command: init
          arguments: -var=-var=AWS_ACCESSKEY=${{ secrets.AWS_ACCESS_KEY_ID }} -var=AWS_SECTRET_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} -var-file=dev-vars.pkrvars.json
          target: ami.pkr.hcl

    # Ref: https://github.com/marketplace/actions/packer-github-actions
    - name: Validate Packer Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        arguments: -var-file=dev-vars.pkrvars.json
        target: ami.pkr.hcl
      env:
        PACKER_LOG: 1 # enable debug log for packer